## Conceitos básicos do R

#### Baseado no curso disponivel gratuitamente em https://campus.datacamp.com/courses/free-introduction-to-r

Codigo para: a recebe 3, b recebe 4, c recebe 3+4

In [8]:
#1
a <- 5
b <- 4
c <- a+b

In [1]:
#2

d <- 4
d

[1] 4

Codigo para imprimir o valor de c

In [9]:
a

[1] 5

Tipos de variaveis: string, numerico e lógico (True e False)

In [2]:
#3
# Mude para 42
var_numerico <- 42.5
var_numerico
class(var_numerico)

# Mude para "universo"
var_caracterer <- "exemplo"
var_caracterer
class(var_caracterer)


# Mude para FALSE
var_logico <- TRUE
var_logico
class(var_logico)

[1] 42.5

[1] "numeric"

[1] "exemplo"

[1] "character"

[1] TRUE

[1] "logical"

Variavel do tipo vetor. Um vetor guarda uma série de dados. Então o vetor tem uma dimensão.

In [11]:
#4

numerico_vetor <- c(1, 10, 49)
caracter_vetor <- c("a", "b", "c")

# Complete o codigo com um vetor logico
boolean_vetor <-

ERROR: Error in parse(text = x, srcfile = src): <text>:6:0: unexpected end of input
4: # Complete o codigo com um vetor logico
5: boolean_vetor <-
  ^


### Considere os dados do seu desempenho num cassino.

In [5]:
#5
# Numeros podem ser positivos ou negativos (Exemplos de ganhos e perdas num jogo de poker de 2a a 6a feira)
poker_vetor <- c(140, -50, 20, -120, 240)

# Exemplos de ganhos e perdas num jogo de roleta de 2a a 6a feira
rouleta_vetor <-  c(-24, -50, 100, -350, 10)

In [6]:
#6
# Atribua os dias da semana pra uma variavel
dias_vetor <- c("Segunda", "Terça", "Quarta", "Quinta", "Sexta")

# Atribua nomes para os valores das colunas do poker_vetor
names(poker_vetor) <- dias_vetor
poker_vetor

# Atribua nomes para os valores das colunas do poker_vetor
names(rouleta_vetor) <- dias_vetor
rouleta_vetor

Segunda   Terça  Quarta  Quinta   Sexta 
    140     -50      20    -120     240

Segunda   Terça  Quarta  Quinta   Sexta 
    -24     -50     100    -350      10

Operacoes vetoriais

In [12]:
#7
A_vector <- c(1, 2, 3)
B_vector <- c(4, 5, 6)

# Somar A_vector e B_vector
total_vector <- A_vector + B_vector
  
# Imprimir total_vector
total_vector

#multiplicar 
multiplicado_vector <- A_vector * B_vector

# Imprimir multiplicado_vector
multiplicado_vector

[1] 5 7 9

[1]  4 10 18

Calcule o saldo diário considerando os ganhos e perdas do jogo de poker e da roleta

In [ ]:
#8
saldo_diario <- 

In [22]:
#9
# Saldo do poker
total_poker <- sum(poker_vetor)

# Saldo da roleta
total_rouleta <- sum(rouleta_vetor)

# Saldo Total 
total_semana <-  

# Imprimir total_semana


In [23]:
#10
# Que ganho foi maior? Do poker ou da roleta?
total_poker > total_rouleta

[1] TRUE

In [32]:
#11
# Valor ganho no poker na Quarta
poker_quarta <- poker_vetor[3]
poker_quarta

Quarta 
    20

In [31]:
#12
# Valores do poker de Terça a Quinta
poker_meiodasemana <- poker_vetor[c(2, 3, 4)]
poker_meiodasemana

Terça Quarta Quinta 
   -50     20   -120

In [ ]:
#13
# Valores da roleta de Terça a Sexta
roulette_selection_vector <- rouleta_vetor[2:5]

In [ ]:
#14
# Selecione os resultados do poker de "Segunda","Terça" e "Quarta"
poker_inicio <- poker_vetor[c("Segunda","Terça","Quarta")]
  
# Calcule a media artimética dos valores do poker_inicio com o comando mean() passando esta variavel como parâmetro


Operadores logicos do R: > , < , == , >= , <= , !=

In [28]:
#15
c(4, 5, 6) > 5

[1] FALSE FALSE  TRUE

In [ ]:
#16
#Em quais dias você ganhou dinheiro?
selecao_vetor <- 
  
#Imprimir o vetor de selecao


In [42]:
#17
# Em quais dias você ganhou dinheiro no poker?
selecao_vetor_poker <- poker_vetor > 0 

selecao_vetor_poker

# Quais são os nomes desses dias
# No exemplo abaixo o R retorna os resultados onde o valor do vetor de seleção é TRUE
poker_dias_ganhos <- dias_vetor[selecao_vetor_poker] 
poker_dias_ganhos

Segunda   Terça  Quarta  Quinta   Sexta 
   TRUE   FALSE    TRUE   FALSE    TRUE

[1] "Segunda" "Quarta"  "Sexta"

In [43]:
#18
# Quanto você ganhou no poker em cada um desses dias?
total_ganhos_poker <- 

# Quanto é a soma desses ganhos ?

Segunda  Quarta   Sexta 
    140      20     240

### Trabalhando com matrix

In [49]:
#19
# A função matrix cria uma matriz com os valores do argumento data. 
# O números de linhas e colunas são definidos pelos argumentos nrow e ncol:
minha.matriz <- matrix(data=1:12, byrow = TRUE, nrow=3,ncol=4)
minha.matriz

minha.matriz <- matrix(data=1:12, byrow = FALSE, nrow=3,ncol=4)
minha.matriz

# Qual a diferença no resultado dos dois comandos acima ?

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [3]:
#20
# Faturamento dos filmes Gerra nas Estrelas (em milhões)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Crie um vetor de dados com o faturamento
faturamento <- c(new_hope, empire_strikes, return_jedi)

# Construa e imprima a matrix com estes dados
star_wars_matrix <- 

In [8]:
#21
#Imprimir a star_wars_matrix
star_wars_matrix

#Selecionar um trecho da matriz. Todos os elementos da 1a linha
#Sintaxe: MATRIZ[LINHAS, COLUNAS]
#Uma unica célula: MATRIZ[1,2]    -   célula na linha 1 e coluna 2
star_wars_matrix[1,2]


[,1]    [,2]   
[1,] 460.998 247.900
[2,] 314.400 309.306
[3,] 290.475 165.800

[1] 247.9

[1] 460.998 314.400 290.475

In [13]:
#22
#Várias células: MATRIZ[1:3,1]   -  células nas linha 1 a 3 e coluna 1
star_wars_matrix[1:3,1]

[1] 460.998 314.400 290.475

In [11]:
#23
#Todas as colunas de uma linha: MATRIZ[1,]   -   todas células da linha 1 
star_wars_matrix[1,]

[1] 460.998 247.900

In [12]:
#24
#Todas as colunas de várias linhas: MATRIZ[1:2,]   -  todas as células da linha 1 a 3 
star_wars_matrix[1:2,]

[,1]    [,2]   
[1,] 460.998 247.900
[2,] 314.400 309.306

### Dataframe

In [ ]:
### Matrizes só armazenam dados de um tipo (Exemplo: ou numeric ou character)
### Como guardar dados lógicos, caracteres e inteiros organizados em colunas e linhas numa só estrutura de dados?
### Use um dataframe


In [36]:
#25
###Ler um arquivo CSV e importar os dados para o R
pisa2015 <- read.csv(file="../../dados/PISA/pisa2015.csv", header=TRUE, sep=";")

#imprimir os primeiros elementos da variável pisa2015
head(pisa2015)

Posicao UF       Matematica Leitura Ciencias NotaMedia
1 13      Acre     377        407     399      394      
2 28      Alagoas  339        362     360      354      
3 21      Amapa    354        385     381      373      
4 12      Amazonas 378        407     399      395      
5 27      Bahia    343        372     368      361      
6  9      Ceará    382        409     401      397

In [17]:
#26
# imprimir a classe da variável pisa2015
class(pisa2015)

[1] "data.frame"

In [22]:
#27
# crie um dataframe com alguns dados de planetas
# Definição dos vetores
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

# Create a data frame from the vectors
planets_df <- data.frame(name, type, diameter, rotation, rings)
head(planets_df)

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE

In [ ]:
#28
# Imprimir o diâmetro de Mercury (linha 1, coluna 3)


# Imprimir os dados de Mars (a 4a coluna inteira)


In [23]:
#29
# Selecione os 5 primeiros valores da coluna diameter
diametro = planets_df[1:5,"diameter"]
diametro

[1]  0.382  0.949  1.000  0.532 11.209

In [24]:
#30
# Selecionar a coluna rings
rings_vector <- planets_df$rings
  
# Imprimir a coluna rings
rings_vector

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE

In [ ]:
#31
#Selecionar o nome de todos os planetas que tem aneis (rings) por meio da coluna rings do dataframe
planets_df[rings_vector, "name"] # O R só retorna as linhas especificadas com TRUE (as linhas 5 a 8)

#Selecionar todas as colunas dos planetas que têm aneis



In [25]:
#32
# Imprimir os diametros menores que 1 (estao na coluna diameter)
planets_df$diameter < 1

[1]  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE

In [ ]:
#33
# Selecionar os planetas com diametro < 1


### Reordenação de vetores

In [27]:
#34
# Construir um vetor a
a <- c(100, 10, 1000)

# Imprimir a ordem os valores do vetor a
order(a)

[1] 2 1 3

In [28]:
#35
# Imprimir a ordem decrescente dos valores do vetor a
order(a, decreasing = TRUE)

[1] 3 1 2

In [29]:
#36
# Imprimir os valores do vetor a reordenados
a[order(a)]

[1]   10  100 1000

In [ ]:
#37
# Mudar a ordem dos elementos do vetor a de forma que eles fiquem em ordem crescente
a <- a[order(a)]

# Imprimir o vetor a
a

In [ ]:
#38
# Imprimir os valores do vetor a reordenados em ordem decrescente


In [ ]:
#39
# Mudar a ordem dos elementos do vetor a de forma que eles fiquem em ordem decrescente


# Imprimir o vetor a
a

In [30]:
#40
# Criar um vetor com numeros positivos e negativos
v2 = c(1, -2, 6, 0, -1, -10)

# Calcular o módulo dos valores do vetor v2
v2_abs = abs(v2)

# Calcular a média dos valores de v2_abs
mean(v2_abs)

# Calcular o desvio padrão dos valores de v2_abs (estudaremos na sequencia o significado de desvio padrão)
sd(v2_abs)

[1] 3.333333

[1] 3.88158

In [33]:
#41
# Criar um vetor com números sequenciais
numeros <- 1:10
numeros

[1]  1  2  3  4  5  6  7  8  9 10

In [38]:
#42
# Calcular o numero de linhas do dataframe pisa2015
nrow(pisa2015)

[1] 27

In [117]:
#43
# Ordenar do dataframe pisa2010 de forma a deixar ordenado em ordem alfabética.
pisa2015 <- pisa2015[order(pisa2015$UF),]
# Imprimir o inicio do dataframe pisa2015.
head(pisa2015)

# Criar um vetor sequencial e adicioná-lo como uma coluna do dataframe
# Esta coluna vai armazenar números que representam a ordem alfabetica por UF
pisa2015$ordem_alfabetica <- 1:nrow(pisa2015) # ordem_alfabetica é o nome escolhido para a nova coluna



Posicao UF       Matematica Leitura Ciencias NotaMedia ordem_alfabetica
1 13      Acre     377        407     399      394       1               
2 28      Alagoas  339        362     360      354       2               
3 21      Amapa    354        385     381      373       3               
4 12      Amazonas 378        407     399      395       4               
5 27      Bahia    343        372     368      361       5               
6  9      Ceará    382        409     401      397       6

In [43]:
#44
# Reordenar o dataframe pisa2015 por ordem decrescente de NotaMedia
pisa2015 <- pisa2015[order(pisa2015$NotaMedia, decreasing = TRUE),]
pisa2015


Posicao UF                  Matematica Leitura Ciencias NotaMedia
8   1      Espirito Santo      405        441     435      427      
16  2      Parana              406        433     425      421      
7   3      Distrito Federal    396        430     426      417      
13  4      Minas Gerais        398        431     422      417      
24  5      Santa Catarina      398        419     418      412      
25  6      Sao Paulo           386        417     409      404      
9   8      Goias               380        416     409      402      
21  7      Rio Grande do Sul   385        410     411      402      
6   9      Ceará               382        409     401      397      
12 10      Mato Grosso do Sul  377        411     403      397      
4  12      Amazonas            378        407     399      395      
1  13      Acre                377        407     399      394      
23 14      Roraima             373        403     398      391      
11 15      Mato Grosso         373        402     396      390      
19 16      Rio de Janeiro      366        400     392      386      
14 17      Para                363        395     386      381      
22 18      Rondonia            364        393     387      381      
17 19      Pernambuco          360        394     383      379      
15 20      Paraiba             357        385     380      374      
3  21      Amapa               354        385     381      373      
18 22      Piaui               355        381     380      372      
20 23      Rio Grande do Norte 353        384     377      371      
26 24      Sergipe             354        379     375      369      
27 25      Tocantins           350        376     372      366      
10 26      Maranhao            343        377     369      363      
5  27      Bahia               343        372     368      361      
2  28      Alagoas             339        362     360      354      
   ordem_alfabetica
8   8              
16 16              
7   7              
13 13              
24 24              
25 25              
9   9              
21 21              
6   6              
12 12              
4   4              
1   1              
23 23              
11 11              
19 19              
14 14              
22 22              
17 17              
15 15              
3   3              
18 18              
20 20              
26 26              
27 27              
10 10              
5   5              
2   2

In [ ]:
#45
# Criar um vetor sequencial e adicioná-lo como uma coluna do dataframe
# Esta coluna vai armazenar números que representam a ordem decrescente de NotaMedia
pisa2015$ordem_notamedia <- 
